# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://caiopia.github.io
title: Caio Lima
email: caio@caiolima.me
description: > # "Overview of Caio Lima"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/caiopia
  - title: linkedin
    url: https://ca.linkedin.com/in/limacaio
  # - title: reverbnation
  #   url: https://www.reverbnation.com/caiolima

